"""Phase 0.5 Step C — PLTR FY22 vs FY23 10-K Risk Factors diff spike.

Fetches PLTR's two most recent 10-Ks (FY22 and FY23 by reporting period),
extracts Part I Item 1A (Risk Factors), and computes the diff in two modes:

  1. Raw — pure paragraph-level diff, no normalization
  2. Normalized — canonical-token normalization applied first
     (dates → <DATE>, currency → <CURRENCY>, pct → <PCT>, big ints → <INT>)

Side-by-side surviving chunks (post-normalization, post-min-words filter)
are written to spike/pltr_10k_riskdiff.md for Ian to review.

Goal: surface 3-5 substantive change examples to seed the Stage 2 few-shot
prompt block (ARCHITECTURE.md §4 / NOTES.md §1).
"""
from __future__ import annotations

import difflib
import re
import sys
from pathlib import Path

from edgar import Company, set_identity

set_identity("Redline hatcher.ry@northeastern.edu")
sys.stdout.reconfigure(encoding="utf-8", errors="replace")

# Stage 1 config (matches ARCHITECTURE.md §4)
DIFF_MIN_WORDS = 22


# ---------- Canonical-token normalization --------------------------------
# Order matters: dates before currency before percentages before integers
# so digits inside dates / dollar amounts aren't caught by later regexes.

DATE_RE = re.compile(
    r"\b("
    r"(?:January|February|March|April|May|June|July|August|September|October|November|December)\s+\d{1,2},?\s+\d{4}"
    r"|\d{1,2}/\d{1,2}/\d{2,4}"
    r"|\d{4}-\d{2}-\d{2}"
    r"|(?:Q[1-4]|Fiscal\s+Year|FY)\s*\d{4}"
    r")\b",
    re.IGNORECASE,
)
CURRENCY_RE = re.compile(
    r"\$\s*\d[\d,]*(?:\.\d+)?\s*(?:billion|million|thousand|B|M|K)?",
    re.IGNORECASE,
)
PCT_RE = re.compile(
    r"\b\d+(?:\.\d+)?\s*(?:%|percent(?:age)?(?:\s+points?)?)\b",
    re.IGNORECASE,
)
INT_RE = re.compile(r"\b\d{3,}\b")  # 3+ digit integers


def normalize(text: str) -> str:
    text = DATE_RE.sub("<DATE>", text)
    text = CURRENCY_RE.sub("<CURRENCY>", text)
    text = PCT_RE.sub("<PCT>", text)
    text = INT_RE.sub("<INT>", text)
    return text


# ---------- Paragraph splitting + filtering ------------------------------

def split_paragraphs(text: str) -> list[str]:
    # Split on blank lines, keep paragraphs as single-line strings
    paras = re.split(r"\n\s*\n+", text)
    # Collapse internal whitespace so trivial line-break differences don't trigger a diff
    return [re.sub(r"\s+", " ", p).strip() for p in paras if p.strip()]


def word_count(s: str) -> int:
    return len(s.split())


# ---------- Diff walker ---------------------------------------------------

def collect_changes(old_paras: list[str], new_paras: list[str]) -> list[dict]:
    """Walk a paragraph-level SequenceMatcher and return change records.

    Each record: {tag: replace|insert|delete, old: str|None, new: str|None}
    Equal blocks are skipped.
    """
    sm = difflib.SequenceMatcher(a=old_paras, b=new_paras, autojunk=False)
    out: list[dict] = []
    for tag, i1, i2, j1, j2 in sm.get_opcodes():
        if tag == "equal":
            continue
        old_chunk = "\n\n".join(old_paras[i1:i2]) if i1 < i2 else ""
        new_chunk = "\n\n".join(new_paras[j1:j2]) if j1 < j2 else ""
        out.append({"tag": tag, "old": old_chunk or None, "new": new_chunk or None})
    return out


def survives_filter(change: dict) -> bool:
    """A change survives Stage 1 if at least one of its chunks meets min_words."""
    return max(
        word_count(change.get("old") or ""),
        word_count(change.get("new") or ""),
    ) >= DIFF_MIN_WORDS


# ---------- Filing fetch --------------------------------------------------

def fetch_pltr_10ks():
    """Return (fy22_filing, fy23_filing) where the period_of_report is around
    those fiscal years. PLTR is calendar-year, so FY22 ends 2022-12-31 and
    is filed Feb 2023; FY23 ends 2023-12-31 and is filed Feb 2024.
    """
    pltr = Company("PLTR")
    all_10k = pltr.get_filings(form="10-K")
    # Sort by period_of_report descending; pick the two we want by year
    by_year = {}
    for f in all_10k:
        pr = getattr(f, "period_of_report", None)
        if pr is None:
            continue
        year = str(pr)[:4]
        if year in ("2022", "2023") and year not in by_year:
            by_year[year] = f
    if "2022" not in by_year or "2023" not in by_year:
        raise RuntimeError(f"Couldn't locate both FY22 and FY23 10-Ks. Found: {list(by_year.keys())}")
    return by_year["2022"], by_year["2023"]


# ---------- Markdown writer ----------------------------------------------

def write_markdown(out_path: Path, raw_changes: list[dict], norm_changes: list[dict],
                   stats: dict) -> None:
    lines: list[str] = []
    lines.append("# PLTR FY22 vs FY23 10-K — Risk Factors diff (Phase 0.5 Step C)")
    lines.append("")
    lines.append("Generated by `spike/pltr_10k_riskdiff_spike.py`.")
    lines.append("")
    lines.append("## Summary statistics")
    lines.append("")
    for k, v in stats.items():
        lines.append(f"- **{k}:** {v}")
    lines.append("")
    lines.append(f"## Surviving chunks (post-normalization, min {DIFF_MIN_WORDS} words)")
    lines.append("")
    lines.append(f"Surviving count: **{len(norm_changes)}**. These are the chunks that the Stage 1 filter would forward to Stage 2.")
    lines.append("")

    if not norm_changes:
        lines.append("_(none — every diff was either cosmetic-token-only or below the min-words threshold)_")
    else:
        for i, c in enumerate(norm_changes, 1):
            tag = c["tag"]
            lines.append(f"### Chunk {i} — `{tag}`")
            lines.append("")
            lines.append("| OLD (FY22) | NEW (FY23) |")
            lines.append("|---|---|")
            old_disp = (c["old"] or "_(nothing)_").replace("\n", "<br>").replace("|", "\\|")
            new_disp = (c["new"] or "_(nothing)_").replace("\n", "<br>").replace("|", "\\|")
            lines.append(f"| {old_disp} | {new_disp} |")
            lines.append("")

    out_path.write_text("\n".join(lines), encoding="utf-8")


# ---------- Main ----------------------------------------------------------

def main():
    print("Fetching PLTR FY22 and FY23 10-Ks...")
    fy22, fy23 = fetch_pltr_10ks()
    print(f"  FY22: {fy22.accession_no}  filed {fy22.filing_date}  period {fy22.period_of_report}")
    print(f"  FY23: {fy23.accession_no}  filed {fy23.filing_date}  period {fy23.period_of_report}")

    print("\nExtracting Part I Item 1A (Risk Factors)...")
    fy22_rf = fy22.obj().get_item_with_part("Part I", "Item 1A")
    fy23_rf = fy23.obj().get_item_with_part("Part I", "Item 1A")
    if not fy22_rf or not fy23_rf:
        print(f"  FY22 RF len: {len(fy22_rf) if fy22_rf else 0}")
        print(f"  FY23 RF len: {len(fy23_rf) if fy23_rf else 0}")
        raise RuntimeError("Empty Risk Factors extraction — investigate before continuing.")
    print(f"  FY22 RF: {len(fy22_rf):,} chars")
    print(f"  FY23 RF: {len(fy23_rf):,} chars")

    # Raw diff
    print("\nRaw paragraph diff (no normalization)...")
    fy22_paras = split_paragraphs(fy22_rf)
    fy23_paras = split_paragraphs(fy23_rf)
    print(f"  FY22 paragraphs: {len(fy22_paras)}")
    print(f"  FY23 paragraphs: {len(fy23_paras)}")
    raw_changes = collect_changes(fy22_paras, fy23_paras)
    raw_surviving = [c for c in raw_changes if survives_filter(c)]
    print(f"  raw diff changes: {len(raw_changes)} total, {len(raw_surviving)} above {DIFF_MIN_WORDS}-word threshold")

    # Normalized diff
    print("\nNormalized paragraph diff (canonical-token normalization first)...")
    fy22_norm = [normalize(p) for p in fy22_paras]
    fy23_norm = [normalize(p) for p in fy23_paras]
    norm_changes_idx = collect_changes(fy22_norm, fy23_norm)
    # Map normalized changes back to original text via paragraph indices
    sm = difflib.SequenceMatcher(a=fy22_norm, b=fy23_norm, autojunk=False)
    norm_changes: list[dict] = []
    for tag, i1, i2, j1, j2 in sm.get_opcodes():
        if tag == "equal":
            continue
        norm_changes.append({
            "tag": tag,
            "old": "\n\n".join(fy22_paras[i1:i2]) if i1 < i2 else None,
            "new": "\n\n".join(fy23_paras[j1:j2]) if j1 < j2 else None,
        })
    norm_surviving = [c for c in norm_changes if survives_filter(c)]
    print(f"  normalized changes: {len(norm_changes)} total, {len(norm_surviving)} above {DIFF_MIN_WORDS}-word threshold")
    print(f"  noise reduction: {len(raw_changes)} → {len(norm_changes)} = {len(raw_changes) - len(norm_changes)} cosmetic-only diffs eliminated")

    stats = {
        "FY22 accession": fy22.accession_no,
        "FY23 accession": fy23.accession_no,
        "FY22 RF chars": f"{len(fy22_rf):,}",
        "FY23 RF chars": f"{len(fy23_rf):,}",
        "FY22 paragraphs": len(fy22_paras),
        "FY23 paragraphs": len(fy23_paras),
        "raw paragraph-diff changes": len(raw_changes),
        "raw changes above min-words": len(raw_surviving),
        "normalized paragraph-diff changes": len(norm_changes),
        "normalized changes above min-words (surviving)": len(norm_surviving),
        "cosmetic-only eliminated by normalization": len(raw_changes) - len(norm_changes),
        "min_words threshold": DIFF_MIN_WORDS,
    }

    out_path = Path(__file__).parent / "pltr_10k_riskdiff.md"
    write_markdown(out_path, raw_changes, norm_surviving, stats)
    print(f"\nMarkdown written to {out_path}")


if __name__ == "__main__":
    main()
